import '../models/location_details.dart';

class LocationDataService {
  LocationDataService._();

  static final LocationDataService instance = LocationDataService._();

  // NOTE: This is a Dart mirror of a subset of LOCATION_DATABASE from locations.js.
  // Add more entries as needed to keep it in sync with the web data.
  final Map<String, LocationDetails> _locationsById = {
    'mtl-mount-royal': LocationDetails(
      id: 'mtl-mount-royal',
      name: 'Mount Royal Park',
      rating: 4.9,
      reviews: '45,000',
      price: 'Free',
      category: 'Park',
      address: 'Mount Royal',
      openStatus: 'Open',
      closeTime: '11 PM',
      phone: null,
      website: null,
      description:
          'Iconic mountain park offering panoramic views of the city, walking trails, and the famous cross.',
      hours: [
        DayHours(day: 'Monday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Tuesday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Wednesday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Thursday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Friday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Saturday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Sunday', time: '6:00 AM – 11:00 PM'),
      ],
    ),
    'mtl-schwartz': LocationDetails(
      id: 'mtl-schwartz',
      name: "Schwartz's Deli",
      rating: 4.6,
      reviews: '18,421',
      price: r'$$',
      category: 'Deli',
      address: '3895 St Laurent Blvd',
      openStatus: 'Open',
      closeTime: '11 PM',
      phone: '(514) 842-4813',
      website: 'https://schwartzsrestaurant.com',
      description: 'The institution. Smoked meat, cherry coke, pickles.',
      hours: [
        DayHours(day: 'Monday', time: '11:00 AM – 11:00 PM'),
        DayHours(day: 'Tuesday', time: '11:00 AM – 11:00 PM'),
        DayHours(day: 'Wednesday', time: '11:00 AM – 11:00 PM'),
        DayHours(day: 'Thursday', time: '11:00 AM – 11:00 PM'),
        DayHours(day: 'Friday', time: '11:00 AM – 11:00 PM'),
        DayHours(day: 'Saturday', time: '11:00 AM – 11:00 PM'),
        DayHours(day: 'Sunday', time: '11:00 AM – 11:00 PM'),
      ],
    ),
    'mtl-notre-dame': LocationDetails(
      id: 'mtl-notre-dame',
      name: 'Notre-Dame Basilica',
      rating: 4.9,
      reviews: '35,000',
      price: r'$$',
      category: 'Basilica',
      address: '110 Notre-Dame St W',
      openStatus: 'Closes soon',
      closeTime: '4:30 PM',
      phone: null,
      website: null,
      description: 'Gothic Revival masterpiece with stunning interior.',
      hours: [
        DayHours(day: 'Monday', time: '9:00 AM – 4:30 PM'),
        DayHours(day: 'Tuesday', time: '9:00 AM – 4:30 PM'),
        DayHours(day: 'Wednesday', time: '9:00 AM – 4:30 PM'),
        DayHours(day: 'Thursday', time: '9:00 AM – 4:30 PM'),
        DayHours(day: 'Friday', time: '9:00 AM – 4:30 PM'),
        DayHours(day: 'Saturday', time: '9:00 AM – 4:30 PM'),
        DayHours(day: 'Sunday', time: '9:00 AM – 4:30 PM'),
      ],
    ),
    'mtl-mcgill': LocationDetails(
      id: 'mtl-mcgill',
      name: 'McGill University',
      rating: 4.8,
      reviews: '15,000',
      price: 'Free',
      category: 'University',
      address: '845 Sherbrooke St W',
      openStatus: 'Open',
      closeTime: null,
      phone: null,
      website: null,
      description: 'Prestigious university with beautiful historic campus.',
      hours: [
        DayHours(day: 'Monday', time: '24 Hours'),
      ],
    ),
    'mtl-dieu-du-ciel': LocationDetails(
      id: 'mtl-dieu-du-ciel',
      name: 'Dieu du Ciel!',
      rating: 4.8,
      reviews: '4,500',
      price: r'$$',
      category: 'Microbrewery',
      address: '29 Laurier Ave W',
      openStatus: 'Open',
      closeTime: '3 AM',
      phone: null,
      website: null,
      description: 'Legendary craft brewery with exceptional Belgian-style beers.',
      hours: [
        DayHours(day: 'Monday', time: '3:00 PM – 3:00 AM'),
        DayHours(day: 'Tuesday', time: '3:00 PM – 3:00 AM'),
        DayHours(day: 'Wednesday', time: '3:00 PM – 3:00 AM'),
        DayHours(day: 'Thursday', time: '3:00 PM – 3:00 AM'),
        DayHours(day: 'Friday', time: '3:00 PM – 3:00 AM'),
        DayHours(day: 'Saturday', time: '3:00 PM – 3:00 AM'),
        DayHours(day: 'Sunday', time: '3:00 PM – 3:00 AM'),
      ],
    ),
    'mtl-st-viateur': LocationDetails(
      id: 'mtl-st-viateur',
      name: 'St-Viateur Bagel',
      rating: 4.9,
      reviews: '15,600',
      price: r'$',
      category: 'Bakery',
      address: '263 Rue Saint-Viateur O',
      openStatus: 'Open 24 hours',
      closeTime: null,
      phone: null,
      website: null,
      description: 'The 24/7 wood-fired bagel temple.',
      hours: [
        DayHours(day: 'Monday', time: '24 Hours'),
        DayHours(day: 'Tuesday', time: '24 Hours'),
        DayHours(day: 'Wednesday', time: '24 Hours'),
        DayHours(day: 'Thursday', time: '24 Hours'),
        DayHours(day: 'Friday', time: '24 Hours'),
        DayHours(day: 'Saturday', time: '24 Hours'),
        DayHours(day: 'Sunday', time: '24 Hours'),
      ],
    ),
    'mtl-parc-lafontaine': LocationDetails(
      id: 'mtl-parc-lafontaine',
      name: 'Parc La Fontaine',
      rating: 4.8,
      reviews: '12,000',
      price: 'Free',
      category: 'Park',
      address: 'Plateau-Mont-Royal',
      openStatus: 'Open',
      closeTime: '11 PM',
      phone: null,
      website: null,
      description: 'The big park. Duck ponds and summer theater.',
      hours: [
        DayHours(day: 'Monday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Tuesday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Wednesday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Thursday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Friday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Saturday', time: '6:00 AM – 11:00 PM'),
        DayHours(day: 'Sunday', time: '6:00 AM – 11:00 PM'),
      ],
    ),
    'mtl-place-ville-marie': LocationDetails(
      id: 'mtl-place-ville-marie',
      name: 'Place Ville Marie',
      rating: 4.6,
      reviews: '2,000',
      price: 'Free',
      category: 'Office Tower',
      address: '1 Place Ville Marie',
      openStatus: 'Open',
      closeTime: '6 PM',
      phone: null,
      website: null,
      description: 'Iconic cruciform tower defining the skyline.',
      hours: [
        DayHours(day: 'Monday', time: '9:00 AM – 6:00 PM'),
        DayHours(day: 'Tuesday', time: '9:00 AM – 6:00 PM'),
        DayHours(day: 'Wednesday', time: '9:00 AM – 6:00 PM'),
        DayHours(day: 'Thursday', time: '9:00 AM – 6:00 PM'),
        DayHours(day: 'Friday', time: '9:00 AM – 6:00 PM'),
        DayHours(day: 'Saturday', time: '10:00 AM – 5:00 PM'),
        DayHours(day: 'Sunday', time: 'Closed'),
      ],
    ),
  };

  LocationDetails? getLocationById(String id) => _locationsById[id];
}

