// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTYq40jhptvV0CUKU48HZW6VeHa22R0Y',
    appId: '1:680993210456:web:72bd95bba0038fff6a0a2d',
    messagingSenderId: '680993210456',
    projectId: 'friendmap-5b654',
    authDomain: 'friendmap-5b654.firebaseapp.com',
    storageBucket: 'friendmap-5b654.firebasestorage.app',
    measurementId: 'G-90ZQNX101H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxjxng0mK7XCdrNKcj5YIQsqEdYFW4SO8',
    appId: '1:680993210456:android:94ad0b1652fb9dc76a0a2d',
    messagingSenderId: '680993210456',
    projectId: 'friendmap-5b654',
    storageBucket: 'friendmap-5b654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWGwnjSUQa3ga4aKOetUR-E66H01bhgs',
    appId: '1:680993210456:ios:8503641f8f09e6d56a0a2d',
    messagingSenderId: '680993210456',
    projectId: 'friendmap-5b654',
    storageBucket: 'friendmap-5b654.firebasestorage.app',
    iosBundleId: 'com.example.friendmapProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWGwnjSUQa3ga4aKOetUR-E66H01bhgs',
    appId: '1:680993210456:ios:8503641f8f09e6d56a0a2d',
    messagingSenderId: '680993210456',
    projectId: 'friendmap-5b654',
    storageBucket: 'friendmap-5b654.firebasestorage.app',
    iosBundleId: 'com.example.friendmapProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADTYq40jhptvV0CUKU48HZW6VeHa22R0Y',
    appId: '1:680993210456:web:4873bd59d20c5dae6a0a2d',
    messagingSenderId: '680993210456',
    projectId: 'friendmap-5b654',
    authDomain: 'friendmap-5b654.firebaseapp.com',
    storageBucket: 'friendmap-5b654.firebasestorage.app',
    measurementId: 'G-6XNFP2LYS6',
  );
}
