import 'dart:convert';
import 'package:firebase_core/firebase_core.dart';
import '../firebase_options.dart';
import '../services/locations_service.dart';

/// Script to upload the 35 base locations to Firebase
/// This should be run once to seed the database
Future<void> main() async {
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final locationsService = LocationsService();

  // The 35 locations from the attached file
  final locationsJson = '''
[
  {
    "id": "mtl-mount-royal",
    "name": "Mount Royal Park",
    "type": "park",
    "rating": 4.9,
    "reviews": "45,000",
    "price": "Free",
    "category": "Park",
    "address": "Mount Royal",
    "openStatus": "Open",
    "closeTime": "11 PM",
    "distance": "1.2 km",
    "coordinates": {"x": 1100, "y": 1000},
    "description": "Iconic mountain park offering panoramic views of the city, walking trails, and the famous cross.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 11:00 PM"}
    ]
  },
  {
    "id": "mtl-summit-woods",
    "name": "Summit Woods",
    "type": "park",
    "rating": 4.8,
    "reviews": "8,500",
    "price": "Free",
    "category": "Park",
    "address": "Westmount",
    "openStatus": "Open",
    "closeTime": "9 PM",
    "distance": "2.1 km",
    "coordinates": {"x": 700, "y": 1400},
    "description": "Beautiful forested area with hiking trails and natural landscapes.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 9:00 PM"}
    ]
  },
  {
    "id": "mtl-oratory",
    "name": "St Joseph's Oratory of Mount Royal",
    "type": "landmark",
    "rating": 4.8,
    "reviews": "28,000",
    "price": "Free",
    "category": "Basilica",
    "address": "3800 Queen Mary Rd",
    "openStatus": "Open",
    "closeTime": "9 PM",
    "distance": "1.8 km",
    "coordinates": {"x": 1200, "y": 850},
    "description": "Canada's largest church, a stunning basilica with beautiful architecture and city views.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 9:00 PM"}
    ]
  },
  {
    "id": "mtl-schwartz",
    "name": "Schwartz's Deli",
    "type": "restaurant",
    "rating": 4.6,
    "reviews": "18,421",
    "price": "$$",
    "category": "Deli",
    "address": "3895 St Laurent Blvd",
    "openStatus": "Open",
    "closeTime": "11 PM",
    "distance": "2.2 km",
    "coordinates": {"x": 1520, "y": 1300},
    "description": "The institution. Smoked meat, cherry coke, pickles.",
    "hours": [
      {"day": "Monday", "time": "11:00 AM – 11:00 PM"},
      {"day": "Tuesday", "time": "11:00 AM – 11:00 PM"},
      {"day": "Wednesday", "time": "11:00 AM – 11:00 PM"},
      {"day": "Thursday", "time": "11:00 AM – 11:00 PM"},
      {"day": "Friday", "time": "11:00 AM – 11:00 PM"},
      {"day": "Saturday", "time": "11:00 AM – 11:00 PM"},
      {"day": "Sunday", "time": "11:00 AM – 11:00 PM"}
    ]
  },
  {
    "id": "mtl-dieu-du-ciel",
    "name": "Dieu du Ciel!",
    "type": "bar",
    "rating": 4.8,
    "reviews": "4,500",
    "price": "$$",
    "category": "Microbrewery",
    "address": "29 Laurier Ave W",
    "openStatus": "Open",
    "closeTime": "3 AM",
    "distance": "3.5 km",
    "coordinates": {"x": 1400, "y": 950},
    "description": "Legendary craft brewery with exceptional Belgian-style beers.",
    "hours": [
      {"day": "Monday", "time": "3:00 PM – 3:00 AM"},
      {"day": "Tuesday", "time": "3:00 PM – 3:00 AM"},
      {"day": "Wednesday", "time": "3:00 PM – 3:00 AM"},
      {"day": "Thursday", "time": "3:00 PM – 3:00 AM"},
      {"day": "Friday", "time": "3:00 PM – 3:00 AM"},
      {"day": "Saturday", "time": "3:00 PM – 3:00 AM"},
      {"day": "Sunday", "time": "3:00 PM – 3:00 AM"}
    ]
  },
  {
    "id": "mtl-st-viateur",
    "name": "St-Viateur Bagel",
    "type": "food",
    "rating": 4.9,
    "reviews": "15,600",
    "price": "\$",
    "category": "Bakery",
    "address": "263 Rue Saint-Viateur O",
    "openStatus": "Open 24 hours",
    "closeTime": "",
    "distance": "3.8 km",
    "coordinates": {"x": 1350, "y": 850},
    "description": "The 24/7 wood-fired bagel temple.",
    "hours": [
      {"day": "Monday", "time": "24 Hours"},
      {"day": "Tuesday", "time": "24 Hours"},
      {"day": "Wednesday", "time": "24 Hours"},
      {"day": "Thursday", "time": "24 Hours"},
      {"day": "Friday", "time": "24 Hours"},
      {"day": "Saturday", "time": "24 Hours"},
      {"day": "Sunday", "time": "24 Hours"}
    ]
  },
  {
    "id": "mtl-parc-lafontaine",
    "name": "Parc La Fontaine",
    "type": "park",
    "rating": 4.8,
    "reviews": "12,000",
    "price": "Free",
    "category": "Park",
    "address": "Plateau-Mont-Royal",
    "openStatus": "Open",
    "closeTime": "11 PM",
    "distance": "3.0 km",
    "coordinates": {"x": 2000, "y": 1400},
    "description": "The big park. Duck ponds and summer theater.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 11:00 PM"}
    ]
  },
  {
    "id": "mtl-parc-westmount",
    "name": "Parc Westmount",
    "type": "park",
    "rating": 4.7,
    "reviews": "6,200",
    "price": "Free",
    "category": "Park",
    "address": "Westmount",
    "openStatus": "Open",
    "closeTime": "10 PM",
    "distance": "2.5 km",
    "coordinates": {"x": 750, "y": 1600},
    "description": "Beautiful urban park with gardens, playgrounds, and sports facilities.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 10:00 PM"}
    ]
  },
  {
    "id": "mtl-vogue-hotel",
    "name": "Vogue Hotel Montreal",
    "type": "hotel",
    "rating": 4.7,
    "reviews": "1,200",
    "price": "$$$$",
    "category": "Luxury Hotel",
    "address": "1425 Rue de la Montagne",
    "openStatus": "Open",
    "closeTime": "",
    "distance": "0.5 km",
    "coordinates": {"x": 1100, "y": 1900},
    "description": "High-end design hotel in the heart of the Golden Square Mile.",
    "hours": [{"day": "Monday", "time": "24 Hours"}]
  },
  {
    "id": "mtl-place-ville-marie",
    "name": "Place Ville Marie",
    "type": "landmark",
    "rating": 4.6,
    "reviews": "2,000",
    "price": "Free",
    "category": "Office Tower",
    "address": "1 Place Ville Marie",
    "openStatus": "Open",
    "closeTime": "6 PM",
    "distance": "0.4 km",
    "coordinates": {"x": 1200, "y": 1950},
    "description": "Iconic cruciform tower defining the skyline.",
    "hours": [
      {"day": "Monday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Tuesday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Wednesday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Thursday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Friday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 5:00 PM"},
      {"day": "Sunday", "time": "Closed"}
    ]
  },
  {
    "id": "mtl-mcgill",
    "name": "McGill University",
    "type": "landmark",
    "rating": 4.8,
    "reviews": "15,000",
    "price": "Free",
    "category": "University",
    "address": "845 Sherbrooke St W",
    "openStatus": "Open",
    "closeTime": "",
    "distance": "0.8 km",
    "coordinates": {"x": 1050, "y": 1650},
    "description": "Prestigious university with beautiful historic campus.",
    "hours": [{"day": "Monday", "time": "24 Hours"}]
  },
  {
    "id": "mtl-museum-fine-arts",
    "name": "Montreal Museum of Fine Arts",
    "type": "attraction",
    "rating": 4.7,
    "reviews": "22,000",
    "price": "$$",
    "category": "Art Museum",
    "address": "1380 Sherbrooke St W",
    "openStatus": "Open",
    "closeTime": "5 PM",
    "distance": "0.9 km",
    "coordinates": {"x": 1080, "y": 1720},
    "description": "Canada's oldest art museum with extensive collections.",
    "hours": [
      {"day": "Monday", "time": "Closed"},
      {"day": "Tuesday", "time": "10:00 AM – 5:00 PM"},
      {"day": "Wednesday", "time": "10:00 AM – 5:00 PM"},
      {"day": "Thursday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Friday", "time": "10:00 AM – 5:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 5:00 PM"},
      {"day": "Sunday", "time": "10:00 AM – 5:00 PM"}
    ]
  },
  {
    "id": "mtl-grande-bibliotheque",
    "name": "Grande Bibliothèque - BAnQ",
    "type": "landmark",
    "rating": 4.6,
    "reviews": "8,500",
    "price": "Free",
    "category": "Library",
    "address": "475 Boul de Maisonneuve E",
    "openStatus": "Open",
    "closeTime": "10 PM",
    "distance": "1.5 km",
    "coordinates": {"x": 1750, "y": 1800},
    "description": "Modern public library with extensive collections and study spaces.",
    "hours": [
      {"day": "Monday", "time": "10:00 AM – 10:00 PM"},
      {"day": "Tuesday", "time": "10:00 AM – 10:00 PM"},
      {"day": "Wednesday", "time": "10:00 AM – 10:00 PM"},
      {"day": "Thursday", "time": "10:00 AM – 10:00 PM"},
      {"day": "Friday", "time": "10:00 AM – 10:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 10:00 PM"},
      {"day": "Sunday", "time": "10:00 AM – 10:00 PM"}
    ]
  },
  {
    "id": "mtl-uniqlo-eaton",
    "name": "UNIQLO Centre Eaton de Montréal",
    "type": "shop",
    "rating": 4.5,
    "reviews": "3,200",
    "price": "$$",
    "category": "Clothing Store",
    "address": "705 Rue Sainte-Catherine O",
    "openStatus": "Open",
    "closeTime": "9 PM",
    "distance": "0.3 km",
    "coordinates": {"x": 1250, "y": 1980},
    "description": "Japanese fast-fashion retailer with quality basics.",
    "hours": [
      {"day": "Monday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Tuesday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Wednesday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Thursday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Friday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Sunday", "time": "10:00 AM – 7:00 PM"}
    ]
  },
  {
    "id": "mtl-quartier-spectacles",
    "name": "Quartier des Spectacles",
    "type": "attraction",
    "rating": 4.7,
    "reviews": "12,000",
    "price": "Free",
    "category": "Entertainment District",
    "address": "Between Ste-Catherine and René-Lévesque",
    "openStatus": "Open",
    "closeTime": "",
    "distance": "0.6 km",
    "coordinates": {"x": 1350, "y": 1920},
    "description": "Cultural and entertainment hub with festivals and events.",
    "hours": [{"day": "Monday", "time": "24 Hours"}]
  },
  {
    "id": "mtl-notre-dame",
    "name": "Notre-Dame Basilica",
    "type": "landmark",
    "rating": 4.9,
    "reviews": "35,000",
    "price": "$$",
    "category": "Basilica",
    "address": "110 Notre-Dame St W",
    "openStatus": "Closes soon",
    "closeTime": "4:30 PM",
    "distance": "1.8 km",
    "coordinates": {"x": 1600, "y": 2200},
    "description": "Gothic Revival masterpiece with stunning interior.",
    "hours": [
      {"day": "Monday", "time": "9:00 AM – 4:30 PM"},
      {"day": "Tuesday", "time": "9:00 AM – 4:30 PM"},
      {"day": "Wednesday", "time": "9:00 AM – 4:30 PM"},
      {"day": "Thursday", "time": "9:00 AM – 4:30 PM"},
      {"day": "Friday", "time": "9:00 AM – 4:30 PM"},
      {"day": "Saturday", "time": "9:00 AM – 4:30 PM"},
      {"day": "Sunday", "time": "9:00 AM – 4:30 PM"}
    ]
  },
  {
    "id": "mtl-arsenal",
    "name": "Arsenal Contemporary Art",
    "type": "attraction",
    "rating": 4.5,
    "reviews": "800",
    "price": "$$",
    "category": "Art Gallery",
    "address": "2020 William St",
    "openStatus": "Closed",
    "closeTime": "",
    "distance": "2.5 km",
    "coordinates": {"x": 1000, "y": 2300},
    "description": "Massive industrial space for contemporary art.",
    "hours": [
      {"day": "Monday", "time": "Closed"},
      {"day": "Tuesday", "time": "11:00 AM – 6:00 PM"},
      {"day": "Wednesday", "time": "11:00 AM – 6:00 PM"},
      {"day": "Thursday", "time": "11:00 AM – 6:00 PM"},
      {"day": "Friday", "time": "11:00 AM – 6:00 PM"},
      {"day": "Saturday", "time": "11:00 AM – 6:00 PM"},
      {"day": "Sunday", "time": "Closed"}
    ]
  },
  {
    "id": "mtl-bota-bota",
    "name": "Bota Bota, spa-sur-l'eau",
    "type": "attraction",
    "rating": 4.6,
    "reviews": "4,800",
    "price": "$$$",
    "category": "Spa",
    "address": "358 Rue de la Commune O",
    "openStatus": "Open",
    "closeTime": "10 PM",
    "distance": "1.9 km",
    "coordinates": {"x": 1450, "y": 2250},
    "description": "Unique floating spa on the St. Lawrence River.",
    "hours": [
      {"day": "Monday", "time": "9:00 AM – 10:00 PM"},
      {"day": "Tuesday", "time": "9:00 AM – 10:00 PM"},
      {"day": "Wednesday", "time": "9:00 AM – 10:00 PM"},
      {"day": "Thursday", "time": "9:00 AM – 10:00 PM"},
      {"day": "Friday", "time": "9:00 AM – 10:00 PM"},
      {"day": "Saturday", "time": "9:00 AM – 10:00 PM"},
      {"day": "Sunday", "time": "9:00 AM – 10:00 PM"}
    ]
  },
  {
    "id": "mtl-marché-atwater",
    "name": "Marché Atwater",
    "type": "shop",
    "rating": 4.7,
    "reviews": "5,500",
    "price": "$$",
    "category": "Market",
    "address": "138 Atwater Ave",
    "openStatus": "Open",
    "closeTime": "6 PM",
    "distance": "2.8 km",
    "coordinates": {"x": 850, "y": 2150},
    "description": "Historic public market with fresh produce, meats, and specialty foods.",
    "hours": [
      {"day": "Monday", "time": "7:00 AM – 6:00 PM"},
      {"day": "Tuesday", "time": "7:00 AM – 6:00 PM"},
      {"day": "Wednesday", "time": "7:00 AM – 6:00 PM"},
      {"day": "Thursday", "time": "7:00 AM – 6:00 PM"},
      {"day": "Friday", "time": "7:00 AM – 6:00 PM"},
      {"day": "Saturday", "time": "7:00 AM – 6:00 PM"},
      {"day": "Sunday", "time": "7:00 AM – 6:00 PM"}
    ]
  },
  {
    "id": "mtl-burton-montreal",
    "name": "Burton Montréal Flagship Store",
    "type": "shop",
    "rating": 4.6,
    "reviews": "1,800",
    "price": "$$$",
    "category": "Sporting Goods",
    "address": "421 Rue Sainte-Catherine O",
    "openStatus": "Open",
    "closeTime": "9 PM",
    "distance": "1.1 km",
    "coordinates": {"x": 1320, "y": 1950},
    "description": "Flagship store for snowboard and outdoor gear.",
    "hours": [
      {"day": "Monday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Tuesday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Wednesday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Thursday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Friday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 9:00 PM"},
      {"day": "Sunday", "time": "10:00 AM – 7:00 PM"}
    ]
  },
  {
    "id": "mtl-parc-jean-drapeau",
    "name": "Parc Jean-Drapeau",
    "type": "park",
    "rating": 4.6,
    "reviews": "18,000",
    "price": "Free",
    "category": "Park",
    "address": "Île Sainte-Hélène",
    "openStatus": "Open",
    "closeTime": "11 PM",
    "distance": "4.2 km",
    "coordinates": {"x": 2100, "y": 2350},
    "description": "Expansive park on the islands with beaches, museums, and events.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 11:00 PM"}
    ]
  },
  {
    "id": "mtl-jardins-floralies",
    "name": "Jardins des Floralies",
    "type": "park",
    "rating": 4.5,
    "reviews": "3,500",
    "price": "Free",
    "category": "Garden",
    "address": "Île Notre-Dame",
    "openStatus": "Open",
    "closeTime": "8 PM",
    "distance": "4.5 km",
    "coordinates": {"x": 2250, "y": 2450},
    "description": "Beautiful gardens from the 1980 World's Fair.",
    "hours": [
      {"day": "Monday", "time": "8:00 AM – 8:00 PM"},
      {"day": "Tuesday", "time": "8:00 AM – 8:00 PM"},
      {"day": "Wednesday", "time": "8:00 AM – 8:00 PM"},
      {"day": "Thursday", "time": "8:00 AM – 8:00 PM"},
      {"day": "Friday", "time": "8:00 AM – 8:00 PM"},
      {"day": "Saturday", "time": "8:00 AM – 8:00 PM"},
      {"day": "Sunday", "time": "8:00 AM – 8:00 PM"}
    ]
  },
  {
    "id": "mtl-jean-dore-beach",
    "name": "Jean-Doré Beach",
    "type": "park",
    "rating": 4.4,
    "reviews": "12,500",
    "price": "$$",
    "category": "Beach",
    "address": "Île Notre-Dame",
    "openStatus": "Temporarily closed",
    "closeTime": "",
    "distance": "4.6 km",
    "coordinates": {"x": 2300, "y": 2480},
    "description": "Urban beach on the St. Lawrence River. Currently closed for the season.",
    "hours": [
      {"day": "Monday", "time": "Closed"},
      {"day": "Tuesday", "time": "Closed"},
      {"day": "Wednesday", "time": "Closed"},
      {"day": "Thursday", "time": "Closed"},
      {"day": "Friday", "time": "Closed"},
      {"day": "Saturday", "time": "Closed"},
      {"day": "Sunday", "time": "Closed"}
    ]
  },
  {
    "id": "mtl-circuit-gilles",
    "name": "Circuit Gilles Villeneuve",
    "type": "attraction",
    "rating": 4.7,
    "reviews": "8,200",
    "price": "Free",
    "category": "Race Track",
    "address": "Île Notre-Dame",
    "openStatus": "Open",
    "closeTime": "9 PM",
    "distance": "4.8 km",
    "coordinates": {"x": 2350, "y": 2520},
    "description": "Formula 1 race track and recreational cycling path.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 9:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 9:00 PM"}
    ]
  },
  {
    "id": "mtl-parc-dieppe",
    "name": "Parc de Dieppe",
    "type": "park",
    "rating": 4.3,
    "reviews": "2,100",
    "price": "Free",
    "category": "Park",
    "address": "Near Île Notre-Dame",
    "openStatus": "Open",
    "closeTime": "10 PM",
    "distance": "4.3 km",
    "coordinates": {"x": 2180, "y": 2420},
    "description": "Riverside park with walking paths and water views.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 10:00 PM"}
    ]
  },
  {
    "id": "mtl-sweater-guys",
    "name": "The Sweater Guys",
    "type": "shop",
    "rating": 4.5,
    "reviews": "850",
    "price": "$$",
    "category": "Clothing Store",
    "address": "1235 Ste-Catherine St W",
    "openStatus": "Open",
    "closeTime": "7 PM",
    "distance": "0.7 km",
    "coordinates": {"x": 1280, "y": 1930},
    "description": "Cozy sweaters and winter wear.",
    "hours": [
      {"day": "Monday", "time": "10:00 AM – 7:00 PM"},
      {"day": "Tuesday", "time": "10:00 AM – 7:00 PM"},
      {"day": "Wednesday", "time": "10:00 AM – 7:00 PM"},
      {"day": "Thursday", "time": "10:00 AM – 7:00 PM"},
      {"day": "Friday", "time": "10:00 AM – 7:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 7:00 PM"},
      {"day": "Sunday", "time": "12:00 PM – 6:00 PM"}
    ]
  },
  {
    "id": "mtl-silkmelody",
    "name": "SilkMelody",
    "type": "shop",
    "rating": 4.4,
    "reviews": "620",
    "price": "$$",
    "category": "Clothing Store",
    "address": "1452 Ste-Catherine St W",
    "openStatus": "Open",
    "closeTime": "8 PM",
    "distance": "0.9 km",
    "coordinates": {"x": 1380, "y": 1940},
    "description": "Fashion boutique with elegant designs.",
    "hours": [
      {"day": "Monday", "time": "10:00 AM – 8:00 PM"},
      {"day": "Tuesday", "time": "10:00 AM – 8:00 PM"},
      {"day": "Wednesday", "time": "10:00 AM – 8:00 PM"},
      {"day": "Thursday", "time": "10:00 AM – 8:00 PM"},
      {"day": "Friday", "time": "10:00 AM – 8:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 8:00 PM"},
      {"day": "Sunday", "time": "12:00 PM – 6:00 PM"}
    ]
  },
  {
    "id": "mtl-hamilton-screen",
    "name": "Hamilton Screen Print",
    "type": "shop",
    "rating": 4.6,
    "reviews": "1,200",
    "price": "$$",
    "category": "Print Shop",
    "address": "892 Ste-Catherine St W",
    "openStatus": "Open",
    "closeTime": "6 PM",
    "distance": "1.2 km",
    "coordinates": {"x": 1180, "y": 1920},
    "description": "Custom screen printing and design services.",
    "hours": [
      {"day": "Monday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Tuesday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Wednesday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Thursday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Friday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Saturday", "time": "10:00 AM – 5:00 PM"},
      {"day": "Sunday", "time": "Closed"}
    ]
  },
  {
    "id": "mtl-palazo",
    "name": "Palazo",
    "type": "restaurant",
    "rating": 4.5,
    "reviews": "2,800",
    "price": "$$$",
    "category": "Italian Restaurant",
    "address": "1677 Ste-Catherine St W",
    "openStatus": "Open",
    "closeTime": "11 PM",
    "distance": "1.4 km",
    "coordinates": {"x": 1420, "y": 1960},
    "description": "Upscale Italian cuisine in an elegant setting.",
    "hours": [
      {"day": "Monday", "time": "5:00 PM – 11:00 PM"},
      {"day": "Tuesday", "time": "5:00 PM – 11:00 PM"},
      {"day": "Wednesday", "time": "5:00 PM – 11:00 PM"},
      {"day": "Thursday", "time": "5:00 PM – 11:00 PM"},
      {"day": "Friday", "time": "5:00 PM – 11:00 PM"},
      {"day": "Saturday", "time": "5:00 PM – 11:00 PM"},
      {"day": "Sunday", "time": "5:00 PM – 10:00 PM"}
    ]
  },
  {
    "id": "mtl-storagemart",
    "name": "StorageMart Mini Entrepôts",
    "type": "shop",
    "rating": 4.2,
    "reviews": "450",
    "price": "$$",
    "category": "Storage",
    "address": "2150 Atwater Ave",
    "openStatus": "Open",
    "closeTime": "6 PM",
    "distance": "3.1 km",
    "coordinates": {"x": 920, "y": 2050},
    "description": "Self-storage facility with various unit sizes.",
    "hours": [
      {"day": "Monday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Tuesday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Wednesday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Thursday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Friday", "time": "9:00 AM – 6:00 PM"},
      {"day": "Saturday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Sunday", "time": "10:00 AM – 4:00 PM"}
    ]
  },
  {
    "id": "mtl-minks",
    "name": "Mink's Haute Couture",
    "type": "shop",
    "rating": 4.8,
    "reviews": "1,100",
    "price": "$$$$",
    "category": "Boutique",
    "address": "1472 Ste-Catherine St W",
    "openStatus": "Open",
    "closeTime": "7 PM",
    "distance": "0.9 km",
    "coordinates": {"x": 1370, "y": 1945},
    "description": "Luxury fashion boutique with designer collections.",
    "hours": [
      {"day": "Monday", "time": "11:00 AM – 7:00 PM"},
      {"day": "Tuesday", "time": "11:00 AM – 7:00 PM"},
      {"day": "Wednesday", "time": "11:00 AM – 7:00 PM"},
      {"day": "Thursday", "time": "11:00 AM – 7:00 PM"},
      {"day": "Friday", "time": "11:00 AM – 7:00 PM"},
      {"day": "Saturday", "time": "11:00 AM – 7:00 PM"},
      {"day": "Sunday", "time": "12:00 PM – 6:00 PM"}
    ]
  },
  {
    "id": "mtl-olympic-stadium",
    "name": "Olympic Stadium",
    "type": "landmark",
    "rating": 4.4,
    "reviews": "10,000",
    "price": "$$",
    "category": "Stadium",
    "address": "4141 Pierre-de Coubertin Ave",
    "openStatus": "Open",
    "closeTime": "5 PM",
    "distance": "6.0 km",
    "coordinates": {"x": 2700, "y": 800},
    "description": "The Big O. Iconic leaning tower.",
    "hours": [
      {"day": "Monday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Tuesday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Wednesday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Thursday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Friday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Saturday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Sunday", "time": "9:00 AM – 5:00 PM"}
    ]
  },
  {
    "id": "mtl-biodome",
    "name": "Biodôme de Montréal",
    "type": "attraction",
    "rating": 4.7,
    "reviews": "25,000",
    "price": "$$$",
    "category": "Museum",
    "address": "4777 Pierre-de Coubertin Ave",
    "openStatus": "Open",
    "closeTime": "5 PM",
    "distance": "6.2 km",
    "coordinates": {"x": 2750, "y": 850},
    "description": "Unique ecosystem museum with four different environments.",
    "hours": [
      {"day": "Monday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Tuesday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Wednesday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Thursday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Friday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Saturday", "time": "9:00 AM – 5:00 PM"},
      {"day": "Sunday", "time": "9:00 AM – 5:00 PM"}
    ]
  },
  {
    "id": "mtl-parc-bernard-landry",
    "name": "Parc Bernard-Landry",
    "type": "park",
    "rating": 4.4,
    "reviews": "3,200",
    "price": "Free",
    "category": "Park",
    "address": "Cité Multimedia",
    "openStatus": "Open",
    "closeTime": "10 PM",
    "distance": "2.8 km",
    "coordinates": {"x": 1500, "y": 2400},
    "description": "Modern urban park with water features and public art.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 10:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 10:00 PM"}
    ]
  },
  {
    "id": "mtl-parc-lachine",
    "name": "Parc René-Lévesque",
    "type": "park",
    "rating": 4.5,
    "reviews": "5,800",
    "price": "Free",
    "category": "Park",
    "address": "Lachine",
    "openStatus": "Open",
    "closeTime": "11 PM",
    "distance": "5.5 km",
    "coordinates": {"x": 500, "y": 2600},
    "description": "Riverside park with cycling paths and waterfront views.",
    "hours": [
      {"day": "Monday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Tuesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Wednesday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Thursday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Friday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Saturday", "time": "6:00 AM – 11:00 PM"},
      {"day": "Sunday", "time": "6:00 AM – 11:00 PM"}
    ]
  }
]
''';

  try {
    final List<dynamic> decoded = jsonDecode(locationsJson);
    final List<Map<String, dynamic>> locations = 
        decoded.map((item) => item as Map<String, dynamic>).toList();
    
    print('Uploading ${locations.length} locations to Firebase...');
    await locationsService.uploadLocations(locations);
    print('Successfully uploaded ${locations.length} locations to Firebase!');
  } catch (e) {
    print('Error uploading locations: $e');
    rethrow;
  }
}
